### PR TITLE
Add ability to add 24h volume and change as attribute

### PR DESCRIPTION
**Pull request by myhrmans**

### CODE REVIEW

**Comment by maureis** [comment]
@heyajohnny would be nice to se these changes :)

**Comment by heyajohnny** [comment]
I'll look into it soon

**Comment by heyajohnny** [comment]
@maureis I'll probably make a different approach. I personally don't like to put all this data in one sensor.
I think I'll split it into different sensors or attributes

**Comment by maureis** [comment]
It's up to you, you are the the boss here ;)

**Comment by heyajohnny** [comment]
@maureis I've just added attributes for volume, change and market_cap.
You can find an example of how to implement it in a template sensor [here](https://github.com/heyajohnny/cryptoinfo)

**Pull request closed without merging**
